### ISSUE TITLE
Failed to install when using Phonegap Build

### ISSUE THREAD

**Issue by aahedi** [TheJKM/cordova-plugin-simple-notification#1]
Halo, I'm using  
PhoneGap (iOS / Android / Windows)
cli-9.0.0 (5.0.1 / 8.0.0 / 7.0.0)

this log from Phonegap Build

```
Subproject Path: CordovaLib
Subproject Path: app
Subproject Path: CordovaLib
Subproject Path: app
6b9d0a513a8af130c06f664c1ac5bcfb609e3188
"plugman-151 install --platform android --project /var/gimlet/tmp/47259896215940/3862570 --plugin https://github.com/TheJKM/cordova-plugin-simple-notification.git --nohooks=.": Fetching plugin "https://github.com/TheJKM/cordova-plugin-simple-notification.git" via git clone
Using shallow clone
Repository "https://github.com/TheJKM/cordova-plugin-simple-notification.git" checked out to git ref "master" at "6b9d0a5".
Installing "cordova-plugin-simple-notification" at "0.0.1" for android
Plugin dependency "cordova-plugin-device@2.0.2" already fetched, using that version.
Dependent plugin "cordova-plugin-device" already installed on android.
Failed to install 'cordova-plugin-simple-notification': CordovaError: Version of installed plugin: "cordova-support-google-services@1.3.2" does not satisfy dependency plugin requirement "cordova-support-google-services@~1.2.1". Try --force to use installed plugin as dependency.
    at /opt/npm-packages/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:557:37
    at _fulfilled (/opt/npm-packages/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/opt/npm-packages/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/opt/npm-packages/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:749:13)
    at /opt/npm-packages/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:509:49
    at flush (/opt/npm-packages/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Version of installed plugin: "cordova-support-google-services@1.3.2" does not satisfy dependency plugin requirement "cordova-support-google-services@~1.2.1". Try --force to use installed plugin as dependency.
```

**Comment by TheJKM** [comment]
Sorry for the late response. You have a dependency problem, as the plugin requires cordova-support-google-services 1.2.x, and you have 1.3.2. 
I don't use Phonegap Build, but with Cordova CLI you can simply run `cordova plugin install cordova-support-google-services@1.2.1`. With Cordova Android 9, you can completely remove the dependency from plugin.xml and add the preference `GradlePluginGoogleServicesEnabled` to your Cordova-android project.

I'll have a look if I can remove the dependency from the plugin while requiring cordova-android 9 or later.
